name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build . --file build/docker/Dockerfile --tag daopmdean/todoapp:latest

      - name: Push to docker hub
        run: docker push daopmdean/todoapp:latest
