name: Pull Request CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image for testing
        run: docker build . --file build/docker/Dockerfile.test --tag todoapp_test

      - name: Run all tests
        run: docker run todoapp_test
